--- #YAML:1.0
name:                HTML-Template-Bundle
version:             2.9_01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Digest::MD5:                   0
    File::Spec:                    0.82
    Scalar::Util:                  0
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
